### PR TITLE
Swift 5 Syntax Conversions & Clean-up warnings.

### PR DESCRIPTION
**Pull request by mbohling**
- Mainly Swift 5.0 syntax changes.
- Dealt with a warning in WeatherDataManager.swift file when removing observer:

```
deinit {
        NotificationCenter.default.removeObserver(locationAuthorizationObserver)
    }
```

Warning: Expression implicitly coerced from 'NSObjectProtocol?' to 'Any'

Solution:
```
deinit {
        if let locationAuthorizationObserver = locationAuthorizationObserver {
            NotificationCenter.default.removeObserver(locationAuthorizationObserver, name: UIApplication.didBecomeActiveNotification, object: nil)
        }
        if let sortingOrientationChangedObserver = sortingOrientationChangedObserver {
            NotificationCenter.default.removeObserver(sortingOrientationChangedObserver, name: Notification.Name(rawValue: kSortingOrientationPreferenceChanged), object: nil)
        }
    }
```
Rather than simply casting the observer to 'Any', it would be safer to ensure that the observers were non-nil.  Also, I made the removal a little more explicit by adding the name parameter.

- Added another commit to deal with an unsafe forced conversion between UINib options Dictionary types.  (This was due to previous changes I had made, so just tightening up my pull request.)

Original Code:
```
  public func instantiate(withOwner ownerOrNil: Any?, options optionsOrNil: [AnyHashable : Any]? = [:]) -> [Any] {
    return UINib(resource: self).instantiate(withOwner: ownerOrNil, options: optionsOrNil)
```
Error: Cannot convert value of type '[AnyHashable : Any]?' to expected argument type '[UINib.OptionsKey : Any]?'

XCode Suggested Fix:

```
  public func instantiate(withOwner ownerOrNil: Any?, options optionsOrNil: [AnyHashable : Any]? = [:]) -> [Any] {
    return UINib(resource: self).instantiate(withOwner: ownerOrNil, options: optionsOrNil as! [UINib.OptionsKey : Any])
  }
```

I thought because the options parameter name "optionsOrNil", it was confusing to default the value to an empty dictionary, ensuring it is actually never nil.

So rather than deal with casting the dictionary as the code above suggested, and for clarity, I proposed the following:

Solution:

```
  public func instantiate(withOwner ownerOrNil: Any?, options optionsOrNil: [UINib.OptionsKey : Any]?) -> [Any] {
    return UINib(resource: self).instantiate(withOwner: ownerOrNil, options: optionsOrNil)
  }
```

### CODE REVIEW

**Comment by erikmartens** [comment]
Hi @mbohling, thank you for your contribution! Please let me know whether your PR is already `ready for review` and I will try to review as soon as possible 👌

**Comment by mbohling** [comment]
Hi @erikmartens, sounds good.  I couldn't figure out how to label to the pull request, I'm guessing it's something to do with the repository's permissions?  

Anwyay, my PR is ready for review when you get the chance.  

Thanks for a great project that is actually not only useful but educational.  Let me know if there are any changes that need to be made!

Thanks,
@mbohling

**Comment by erikmartens** [comment]
Hey @mbohling, 
sorry for the delay. I was very busy with uni and work. I'll merge your PR now and add you to the list of contributors (let me know if you want you real name their and any special link). I'll clean up the project soon and will make a release. 

Thank you very much for your input!

**Comment by mbohling** [comment]
Hi @erikmartens,

No worries!  Glad I could contribute effectively.  As far as the contributor list, no need to add anything else, appreciate it!

Thanks,
@mbohling

**Pull request merged**
