### PR TITLE
#96 #160 - Dark Mode Support, french wordings fixes

### LINKED ISSUE #96: Dark Mode Support
Similarly to `Constants` there should be `Theme` which defines semantics colours for all required use cases.

All colours should no longer be defined through storyboard, but programmatically.

App needs to listen to `AppDidBecomeActive`-notification to update colours if needed.

### PR DESCRIPTION
**Pull request by pylapp**
**Related issue: #96*, #160* 

Definition Of Done:
- [x] Define kind of theme to apply for dark mode
- [x] Deal with dark mode settings
- [x] Update details about contributions
- [x] Fix french wording
- [x] Add licenses of open source third-party tools to make project more compliant

Closes #96, #160

### CODE REVIEW

**Comment by erikmartens** [comment]
Hey @pylapp, good to see you back. Looking forward to your finished contribution!

**Comment by pylapp** [comment]
Here are some screen shots about the implemented dark mode.

#96 - API key screen
#96 - permision screen
#96 - list
#96 - about
#96 - map

**Comment by erikmartens** [comment]
Hey @pylapp, thanks for your work, looks great already! From you todo list above it looks that you want to do some more work? Let me know when it is ready for review 👍 I'm looking forward to checking out the completed work 😃 

I have 2 requests regarding the design:
- The hint-bubbles in the Welcome Scenes should have the same background color as tableview cells and no outline border
- Can you make the navigation bars look like they for example look like in the system settings (they have a slight transparency and are a bit lighter than #000000:

IMG_0FF5E824F887-1

Also feel free to join my Discord Server: https://discord.gg/fxPgKzC I'm still in the process of setting it up, but it will be easier to discuss things there.

**Comment by pylapp** [comment]
Hi @erikmartens!

You can consider my pull request is now ready for review.

I implemented a first solution of dark mode (#96), and also brought some typo fixe for french localization (#160).

In a nutshell, no big change in the project, but thee evolutions:
- a Group folder with the boilerplate files
- some custom view controllers to deal with delegate notifications
- extension of UIColor to make colors lighter or darker
- update of storyboards so remove hard-defined colors and make theme clear

No big changes in colors ; for weather detail and map annotations I use the day/Night colors and make them darker if dark mode is in use.

Feel free to review the code and improve it, I am not used to RxFlow (>_<)

Cheers!

**Comment by pylapp** [comment]
> Hey @pylapp, thanks for your work, looks great already! From you todo list above it looks that you want to do some more work? Let me know when it is ready for review 👍 I'm looking forward to checking out the completed work 😃
> 
> I have 2 requests regarding the design:
> 
> * The hint-bubbles in the Welcome Scenes should have the same background color as tableview cells and no outline border
> * Can you make the navigation bars look like they for example look like in the system settings (they have a slight transparency and are a bit lighter than #000000:
> 
> IMG_0FF5E824F887-1
> 
> Also feel free to join my Discord Server: https://discord.gg/fxPgKzC I'm still in the process of setting it up, but it will be easier to discuss things there.

Yep, it's done :-)

**Comment by erikmartens** [comment]
@pylapp Awesome, thanks for letting me know. And thanks again for your contribution! I'll test and review your code during the next days 👍 Looking forward to getting this merged 😃

**Comment by pylapp** [comment]
Hello @erikmartens!
Are you ok with thus pull request?
Let me know if there are things to add :)
Cheers!

**Pull request closed without merging**
