### PR TITLE
Refactor of project filetree

### PR DESCRIPTION
**Pull request by pylapp**
Refactored the project file tree to make the project more compilant with FLOSS projects structures

- (Previously update local branches with the last commits from upstream)
- Add licenses of third-party tools in folder
- Compile third-party tools in a file
- List contributors in a file

### CODE REVIEW

**Comment by pylapp** [comment]
Hi Erik!

Huuu woops I will remove the pods, my bad!

Interesting idea about the AUTHORS.md file generation, event if we can find such file in repositories the idea to create it based on JSON data is interesting. I should work on it, a dumb Shell script can do the job easily.

About the licenses it can be more touchy. In most of cases having a copy of the license is recommended because of the license itself (mandatory in some cases) or so as to be sure the project is compliant. Open source world can be a real mess, that is the reason why in some companies like mine (Orange) we like to create a folder with the headers of the third party tools in use. Thus if an issue about compatibility or license compliance is thrown, we may be able to say something like “hey guys, our commits ensures when we used your lib it was under these conditions”. I agree that we have to keep it up-to-date manually but from my point of view it is a good practice to list these elements. Though MIT license is quite cool with it ^^ Interesting idea about a solution which can get license headers automatically indeed :)

I will update my PR tomorrow maybe :)

Cheers,

**Comment by pylapp** [comment]
- Pods removed at commit 96acfb197aa0f1fd3f3e951d2f0d50ef067db1f6
- .gitignore updated at commit 0618e7114318e434aefc66b1321d30ee1273f408

**Comment by pylapp** [comment]
- Wrote a Python script triggered from the Build Phases of Xcode to read the JSON file of contributors and produce a MarkDown-based AUTHORS file (at commit a9f07405ebe1211f39558114e31b955b20e2c8cf)

**Comment by pylapp** [comment]
To my mind this pull request might me accepted? Even if an automatic solution . for licenses has not been implemented yet.

**Comment by erikmartens** [comment]
I'm closing this now since it has become stale. Feel free to re-open after the fixes were implemented :)

**Pull request closed without merging**
